architecture: emp-gcn-nci
batch_size: 800
config: log/emp-gcn-nci/emp-gcn-nci-grid001
dataset: NCI1
device: cuda
dropout_ratio: 0
epochs: 120
evaluation_steps: 1
evaluation_strategy: steps
experiment_name: emp-gcn-nci-grid
experiment_name_suffix: ''
greater_better: true
lamb: 1
load_best: true
log_path: log/emp-gcn-nci-grid
log_steps: 1
logging: true
logging_strategy: steps
lr: 1e-03
nhid: 128
num_classes: 2
num_features: 37
num_workers: 4
output_path: model/emp-gcn-nci-grid
pooling_ratio: 0.3
pruning: true
random_seed: 21
resume_from_checkpoint: false
sample_neighbor: true
save_limits: 5
save_steps: 100
save_strategy: steps
sparse_attention: true
split_ratio: 0.5
structure_learning: true
task_type: statistical-gcn
test_ratio: 0.5
