architecture: hgp-frank
batch_size: 600
custom_trainer: TrainerDiceLoss
dataset: FRANKENSTEIN
device: cuda
dropout_ratio: 0.0017571109892678656
epochs: 8
evaluation_steps: 1
evaluation_strategy: steps
experiment_name: hpt-frank
experiment_name_suffix: ''
greater_better: true
lamb: 1
load_best: true
log_path: log/frank/hpt-frank
log_steps: 1
logging: true
logging_strategy: steps
lr: 1e-03
lr_scheduler_type: linear
metric_used: matthews_correlation
nhid: 206
num_classes: 2
num_features: 780
num_workers: 4
output_path: model/frank/hpt-frank
patience: 100
pooling_ratio: 0.17282936148773426
pruning: true
random_seed: 42
resume_from_checkpoint: false
sample_neighbor: true
save_limits: 5
save_steps: 100
save_strategy: steps
sparse_attention: true
split_ratio: 0.7
structure_learning: true
task_type: graph classification
test_ratio: 0.5
warm_up: 1/5
weight_decay: 1e-03
